const GlobalVars = {
    backendIP: "https://backend2.rzak.eu/",
    nazwaTrybuERS: ["None", "Medium", "Hotlap", "Overtake"],
    typOponWizualnie: {
		16: "Soft",
		17: "Medium",
		18: "Hard",
		7: "Inter",
		8: "Wet",
		15: "Wet",
		19: "Ultra Soft",
		20: "Soft",
		21: "Medium",
		22: "Hard"
	},
    trybPaliwo: ["Lean", "Normal", "Rich"],
    typOpon: {
		16: "C5",
		17: "C4",
		18: "C3",
		19: "C2",
		20: "C1",
		7: "Inter",
		8: "Wet"
	},
    teamIds: {
        0: 'Mercedes',
        1: 'Ferrari',
        2: 'Red Bull Racing',
        3: 'Williams',
        4: 'Aston Martin',
        5: 'Alpine',
        6: 'Alpha Tauri',
        7: 'Haas',
        8: 'McLaren',
        9: 'Alfa Romeo',
        85: 'Mercedes 2020',
        86: 'Ferrari 2020',
        87: 'Red Bull 2020',
        88: 'Williams 2020',
        89: 'Racing Point 2020',
        90: 'Renault 2020',
        91: 'Alpha Tauri 2020',
        92: 'Haas 2020',
        93: 'McLaren 2020',
        94: 'Alfa Romeo 2020',
        95: 'Aston Martin DB11 V12',
        96: 'Aston Martin Vantage F1 Edition',
        97: 'Aston Martin Vantage Safety Car',
        98: 'Ferrari F8 Tributo',
        99: 'Ferrari Roma',
        100: 'McLaren 720S',
        101: 'McLaren Artura',
        102: 'Mercedes AMG GT Black Series Safety Car',
        103: 'Mercedes AMG GTR Pro',
        104: 'F1 Custom Team',
        106: 'Prema ‘21',
        107: 'Uni-Virtuosi ‘21',
        108: 'Carlin ‘21',
        109: 'Hitech ‘21',
        110: 'Art GP ‘21',
        111: 'MP Motorsport ‘21',
        112: 'Charouz ‘21',
        113: 'Dams ‘21',
        114: 'Campos ‘21',
        115: 'BWT ‘21',
        116: 'Trident ‘21',
        117: 'Mercedes AMG GT Black Series'
    },
    trackIds: ["Melbourne (Australia)", "Paul Ricard", "Shanghai", "Sakhir (Bahrain)", "Catalunya (Spain)",
            "Monaco", "Montreal", "Silverstone (UK)", "Hockenheim (Germany)", "Hungaroring (Hungary)", "Spa (Belgium)",
            "Monza (Italy)", "Singapore","Suzuka (Japan)", "Abu Dhabi", "Texas (USA)", "Brazil", "Austria",
            "Sochi (Russia)", "Mexico", "Baku (Azerbaijan)", "Sakhir Short", "Silverstone Short",
            "Texas Short", "Suzuka Short", "Hanoi", "Zandvoort (Netherlands)", "Imola (Italy)", "Portimão",
            "Jeddah", "Miami (USA)"
    ],
    typKary: [
        "Drive through", 
        "Stop Go", 
        "Grid penalty", 
        "Penalty reminder", 
        "Time penalty", 
        "Warning", 
        "Disqualified", 
        "Removed from formation lap", 
        "Parked too long timer", 
        "Tyre regulations", 
        "This lap invalidated", 
        "This and next lap invalidated", 
        "This lap invalidated without reason", 
        "This and next lap invalidated without reason", 
        "This and previous lap invalidated", 
        "This and previous lap invalidated without reason", 
        "Retired", 
        "Black flag timer"
    ],
    sessionType: ["Unknown", "Practice 1", "Practice 2", "Practice 3", "Short Practice", "Qualification 1", "Qualification 2", "Qualification 3", "Short Race", "OSQ", "Race", "Race 2", "Race 3", "Time Trial"],
    lapTimeFormat: (ms, okr) => {
		if(!ms) return;
		if(okr)	return(<>{(parseInt(ms/60000) < 10) ? "0"+parseInt(ms/60000) : parseInt(ms/60000)}:{(parseInt((ms/1000)%60) < 10) ? "0"+parseInt(ms/1000)%60 : parseInt(ms/1000)%60}.{(parseInt(ms%1000) < 100) ? ((parseInt(ms%1000) < 10) ? "00"+parseInt(ms%1000) : "0"+parseInt(ms%1000)) : parseInt(ms%1000)}</>);
		else return(<>{(parseInt(ms/1000) < 10) ? "0"+parseInt(ms/1000) : parseInt(ms/1000)}.{(parseInt(ms%1000) < 100) ? ((parseInt(ms%1000) < 10) ? "00"+parseInt(ms%1000) : "0"+parseInt(ms%1000)) : parseInt(ms%1000)}</>);
	}
};
export default GlobalVars;